version: "3.7"
services:
  # MySQL
  mysql:
    image: mysql:latest
    volumes:
      - ./pkg/configs/sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=gorm
      - MYSQL_USER=gorm
      - MYSQL_PASSWORD=gorm
      - MYSQL_RANDOM_ROOT_PASSWORD="yes"

  # ETCD TODO
  Etcd:
    image: 'bitnami/etcd:latest'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - "2379:2379"
      - "2380:2380"

  # Collector TODO
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    platform: linux/arm64/v8 # Mac M1 enable, linux disable
    command: [ "--config=/etc/otel-collector-config.yaml", "${OTELCOL_ARGS}" ]
    volumes:
      - ./pkg/configs/otel/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888"        # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "55679"       # zpages extension
    depends_on:
      - jaeger-all-in-one

  # Jaeger TODO
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"
      - "14268"
      - "14250:14250"
      - "6831:6831"

  # Victoriametrics TODO
  victoriametrics:
    container_name: victoriametrics
    image: victoriametrics/victoria-metrics
    ports:
      - "8428:8428"
      - "8089:8089"
      - "8089:8089/udp"
      - "2003:2003"
      - "2003:2003/udp"
      - "4242:4242"
    command:
      - '--storageDataPath=/storage'
      - '--graphiteListenAddr=:2003'
      - '--opentsdbListenAddr=:4242'
      - '--httpListenAddr=:8428'
      - '--influxListenAddr=:8089'
    restart: always

  # Grafana TODO
  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"

#  #
#  portainer:
#    image: portainer/portainer
#    container_name: portainer
#    restart: always
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#      - /tmp/portainer_data:/data
#    ports:
#      - 9000:9000

  redis:
    image: redis:4.0.1
    container_name: redis-label
    volumes:
      - /apps/redis/datadir:/data
      - /apps/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - /apps/redis/logs:/logs
    command: redis-server --requirepass yourpass
    #   #  两个写入操作 只是为了解决启动后警告 可以去掉
    #    /bin/bash -c "echo 511 > /proc/sys/net/core/somaxconn
    #    && echo never > /sys/kernel/mm/transparent_hugepage/enabled
    #    && redis-server /usr/local/etc/redis/redis.conf"
    ports:
      # 使用宿主机的端口映射到容器的端口
      # 宿主机：容器
      - 6379:6379

  zookeeper:
    image: wurstmeister/zookeeper
    restart: always
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka
    restart: always
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181/kafka
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_BROKER_ID: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

#  nginx: #jenkins服务/其他服务（web服务/nginx服务等）
#    image: nginx:1.22  #nginx镜像，如果镜像容器没有会去自动拉取
#    container_name: nginx       #容器的名称
#    restart: always             #跟随docker的启动而启动
#    volumes: #挂载卷命令
#      - /apps/nginx/conf/nginx.conf:/etc/nginx/nginx.conf              #映射配置文件入口文件
#      - /apps/nginx/html:/usr/share/nginx/html                         #静态资源根目录挂载
#      - /apps/nginx/logs:/var/log/nginx                                #日志文件挂载
#      - /apps/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf #映射配置文件
#    ports:
#      - 8080:8080    #宿主主机端口80 映射到 容器端口80